### ISSUE TITLE
Suggestion for script change

### ISSUE THREAD

**Issue by StevenACoffman** [mhausenblas/eksphemeral#1]
`aws eks describe-cluster --name ${CLUSTER_NAME}  --query cluster.endpoint --output text`
is equivalent to:
`aws cloudformation describe-stacks --stack-name eksp | jq '.Stacks[].Outputs[] | select(.OutputKey=="EKSphemeralAPIEndpoint").OutputValue' -r)`

See https://github.com/mhausenblas/eksphemeral/blob/dcb09ca97b50e568b5a8a88b064f79d4126e538d/eksp-create.sh#L79

**Comment by mhausenblas** [comment]
Thank you very much @StevenACoffman and will take that on board!

**Comment by mhausenblas** [comment]
Just thought about it for a little and I'm unsure about if I understand correctly what you're suggestion:

1. What I do with `aws cloudformation describe-stacks --stack-name eksp | jq '.Stacks[].Outputs[] | select(.OutputKey=="EKSphemeralAPIEndpoint").OutputValue' -r)` is to get the HTTP base URL of the EKSphemeral control plane (the API Gateway URL).
2. What you're suggesting with `aws eks describe-cluster --name ${CLUSTER_NAME} --query cluster.endpoint --output text` is the API server URL of an EKS cluster, managed by EKSphemeral. 

Mind explaining how 1. and 2. are equivalent? :)

**Comment by StevenACoffman** [comment]
Ah, my mistake. Many apologies! I mistook OutputKey of `EKSphemeralAPIEndpoint` for `Endpoint`
